# Generated by Django 5.0.7 on 2024-07-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('code_id', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('office_hours', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('students', models.ManyToManyField(related_name='teacher', to='student.student')),
            ],
        ),
    ]
