# Generated by Django 5.0.7 on 2024-07-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_code_id_teacher_teacher_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='code_id',
        ),
    ]
