# Generated by Django 5.0.7 on 2024-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_end_date',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='class_start_date',
        ),
        migrations.AddField(
            model_name='classroom',
            name='number_of_groups',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
    ]
