# Generated by Django 5.0.7 on 2024-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_classroom_class_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_art',
            field=models.CharField(default='Orange triangles', max_length=20),
            preserve_default=False,
        ),
    ]
