# Generated by Django 5.0.7 on 2024-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroom_class_art'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='name',
            new_name='class_name',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.ManyToManyField(related_name='teacher', to='teacher.teacher'),
        ),
    ]
