# Generated by Django 5.0.7 on 2024-07-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_rename_name_classroom_class_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='class_name',
            new_name='name',
        ),
    ]
